### ISSUE TITLE
Avoid application of the Savitzky-Golay filter during pursuit identification

### ISSUE THREAD

**Issue by simkovic** [psychoinformatics-de/remodnav#18]
In order to identify the pursuit events the gaze coordinates are filtered by both the Savitzky-Golay filter and the Butterworth filter, correct? Isn't the application of the SG filter counter-productive in this case? As far as I know, the Butterworth filter is motivated by its flat gain in the pass band, which ensures that the velocity profile of the pursuit eye movement remains intact. In contrast, the SG filter does not have this property and the SG-filtering would affect and bias the velocity distribution.

IMO, the threshold-based pursuit identification should be performed with the gaze data filtered exclusively with the Butterworth filter. The parameter choice does not allow for such adjustment, correct? If I set `savgol_length=0` this would disable SG filter completely for extraction of all events, correct?

**Comment by adswa** [comment]
> In order to identify the pursuit events the gaze coordinates are filtered by both the Savitzky-Golay filter and the Butterworth filter, correct?

I have to load the details of this algorithm into my head, but if I recall correctly (and judging from figure 1 of the corresponding paper), Savitzky-Golay filter and Butterworth filter are applied in different parts of data processing in the algorithm. When one uses the Savitzky-Golay filter, it is applied at preprocessing for all samples. Pursuit detection happens on top of the preprocessed data, so the Butterworth filter that is applied to all remaining samples that need to be classified into either smooth pursuit or fixation is indeed applied on top of Savitzky-Golay filtered data.

> The parameter choice does not allow for such adjustment, correct? If I set savgol_length=0 this would disable SG filter completely for extraction of all events, correct?

correct, yes.

> Isn't the application of the SG filter counter-productive in this case? As far as I know, the Butterworth filter is motivated by its flat gain in the pass band, which ensures that the velocity profile of the pursuit eye movement remains intact. In contrast, the SG filter does not have this property and the SG-filtering would affect and bias the velocity distribution.

If you would want to test this, you could implement this change in the source code of this algorithm and run our executable paper (https://github.com/psychoinformatics-de/paper-remodnav/) on your changes. This should allow you to evaluate algorithm performance on three different datasets, and you could check if a change like the one you propose improves the performance compared to the current algorithm. :)

**Comment by simkovic** [comment]
I don't think that the application of SG filter negatively affects the pursuit event classification. In studies of pursuit eye movements, the velocity profile is often of interest as it indicates the observer's ability to track a moving object. It's unfortunate that the velocity computed by remodnav is unsuitable to tackle such research question.

Anyway, thank You for the clarification. I will look into adapting remodnav for my research.
