### ISSUE TITLE
CI: Appveyor git-annex installtion 404's

### ISSUE THREAD

**Issue by adswa** [psychoinformatics-de/remodnav#33]
During environment setup, Appveyor tries to download http://ftp.us.debian.org/debian/pool/main/g/git-annex/git-annex_8.20201127-1_amd64.deb, which 404's. We could maybe use ftp.us.debian.org/debian/pool/main/g/git-annex/git-annex_8.20210903-1_amd64.deb, @mih?

**Comment by mih** [comment]
Yes! But not with this particular URL. See here for an analog change in datalad

https://github.com/datalad/datalad/pull/5966/files

**Comment by adswa** [comment]
thx, I have replaced the URL
