### ISSUE TITLE
Type error in Savitzky-Golay filter

### ISSUE THREAD

**Issue by a-lakh** [psychoinformatics-de/remodnav#37]
Line 131 in _savitzky_golay.py needs to be 
y = np.zeros(int(polyorder) + 1)
instead of 
y = np.zeros(polyorder + 1)

The current code does not allow a change in the --savgol-polyord parameter

**Comment by adswa** [comment]
Hey, I'm sorry I haven't seen this issue earlier.
The piece of code you are referring to is not part of this Python package. I think you're actually pointing to a module within within Scipy, and I guess Scipy would also be the place to file any issue to. As there is nothing we can do about this on our end as far as I can see I'm closing this, but please reopen if this assessment is wrong and help me understand what can be done.
