### ISSUE TITLE
remodnav and large viewing angles?

### ISSUE THREAD

**Issue by joriswvanrijn** [psychoinformatics-de/remodnav#40]
Dear @AsimHDar, @adswa , @mih,

Thank your for your clear code and documentation. Understanding your research has given us much insights and inspiration for our own challenges.

As part of a research group of the Amsterdam UMC, we are considering using your algorithm for the event detection of our eye tracker. We are aiming to develop a method (using the Pupil Core Eye Tracker) to analyze viewing behavior under circumstances as natural as possible, on a 1.55m wide screen and while allowing for free head movements. We aim to analyze Areas of Interest, as well as perform Event Detection on the gaze data. For the latter purpose, we are exploring using remodnav.

Whilst conceptually understanding your code, we have identified a potential issue with our setup and we were wondering if you had encountered this as well. Since our screen is very wide (1.55m) the viewing angle could be up to 100 degrees. Our understanding is that transforming pixels to degrees based on the `px2deg` factor (as done in https://github.com/psychoinformatics-de/remodnav/blob/master/remodnav/clf.py#L280) would not work with our setup, since distances at the peripheries would transform to much smaller angles as compared to distance located at the centre.

I was wondering if you had encountered this problem as well. Reading this, do you have any thoughts or suggestions how to go about this?

Thank you for your efforts.

Kind regards,
Joris W. van Rijn

**Comment by adswa** [comment]
Hi, happy to hear that our work was helpful! We didn't encounter this problem in our own work, though, the largest monitor we  used before was just a third of the width of yours, and participants did not move their head - so I'm sadly unable to help here. If I remember correctly, though, our pix2deg conversion was based on the original implementation of an eye movement classification algorithm by Nyström and Holmqvist (2010). You might find the expertise needed for a more clever conversion in those two authors? Sorry again that I'm not of much help.
