### ISSUE TITLE
velocities in the output file

### ISSUE THREAD

**Issue by patrickshas** [psychoinformatics-de/remodnav#46]
Hello,
Thank you for this great repo.
A question: Is the command line output figure supposed to provide the plotted velocities as well (as provided in the plots in the published paper)?
Thanks in advance,
Best regards

**Comment by adswa** [comment]
Hi! The function ``show_gaze`` should add the velocities as a grey lineplot on top of the classification visualization. See for example the comments in this issue for example plots and code: https://github.com/psychoinformatics-de/remodnav/issues/28. Are you having trouble with the plots?

**Comment by adswa** [comment]
Hey! A quick second ping on this :) Do you still see some problems?

**Comment by adswa** [comment]
To resolve a bit of clutter I'll close this issue as I believe its addressed. If you think that's a mistake, please feel free to re-open this issue, or open a new one with a new question. Thanks! :)
