### ISSUE TITLE
Smooth Pursuit Detection and Output Precision

### ISSUE THREAD

**Issue by HuskerHeel** [psychoinformatics-de/remodnav#49]
Thank you for hosting this software! After some testing, I noticed like others that using the default precision values in output data result in funky results. For example, in the events_summary_default.png below the main sequence and fixation locations are off; however, when changing the precision to .5 in clf.py the output looks as expected (events_summary_5precision.png). 

After processing a data file with intentional smooth pursuits (following moving cars in a video), I'm not seeing any smooth pursuit labels in the event output. I used all default settings except increasing saccade duration to .02 and noise factor to 7. I also tried with smooth pursuit velocity at 1 and still did not get pursuit labels. The pursuits are evident in the eye traces. Do you have any suggestions on what may be causing this issue?  The event output values (e.g. saccade velocity) need to be multiplied by 1000 to put in deg/sec. Plotting the fixation velocity values in the event output by 1000 shows velocities above the smooth pursuit threshold. I'm wondering if the win_vels values in clf.py need to be multiplied by 1000 as well? I attached the raw input data here (in .zip - eye_positions.tsv) in case it helps diagnose. Thank you for your help and any feedback!

![events_summary_default](https://user-images.githubusercontent.com/25234327/236369781-120c3987-50b8-4239-b2ac-55891fd854df.png)

![events_summary_5precision](https://user-images.githubusercontent.com/25234327/236371059-01cae48d-8177-4de1-9d04-f023991d322f.png)

[2023-05-04-20-59-51.zip](https://github.com/psychoinformatics-de/remodnav/files/11403030/2023-05-04-20-59-51.zip)

**Comment by adswa** [comment]
Hey, thanks for the issue and for attaching data, this helps to take a look.
I don't have an immediate idea, but what stuck me as odd is that the computed velocities and amplitudes are super small. The eye_position.tsv files has x and y positions that almost all in the range of 0, 1 - could it be that the decimal place is wrong in the input data? Movements of a fraction of a pixel look a bit odd to me given the screen resolution in your configuration file.

**Comment by HuskerHeel** [comment]
That would make the most sense. Thank you for the suggestion. I'll take a
look.

**Comment by adswa** [comment]
Hey @HuskerHeel, I hope you were able to resolve your issue :) As I haven't heard back, I will close this issue, hoping that it got fixed. But if there is still something wrong that you'd suspect relates this this library, please feel free to reopen this at any point, or create a new issue :) Thanks!
